### ISSUE TITLE
Collect current STEMS and optical research into a brief document (mini paper?) 

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/moonrat#10]
Nathan and Allana have found some great research papers. I think we should put these in the README on the main website or in a REc folder dedicate to that purpose. I recommend we write a single pararaph summary of each paper for our own purposes.

**Comment by cfergu11** [comment]
I think this should be part of a REc Project repo - do you think that is reasonable @RobertLRead?

**Comment by RobertLRead** [comment]
Yes. I think the work is separate enough it deserves to be separate repo. Please reply to this confirming, and I will create a sperate repo, and you and the REc researchers can start building it out.

**Comment by cfergu11** [comment]
Agreed, let's do that.
