### ISSUE TITLE
PCB Rev 0.1,  DRC 16 Errors, 76 Warnings

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#100]
After updating the PCB from the Schematic after fixing the schematic ECRs I did a DRC on the PCB.

![image](https://github.com/PubInv/moonrat/assets/5836181/b8c3b2d0-0177-4657-a2c0-7fa92369d122)

**Comment by ForrestErickson** [comment]
There is also no Rev in the title block. (Fill out the properties dialog to correct this.)
The page size should be changed from A4 to Letter .

![image](https://github.com/PubInv/moonrat/assets/5836181/ff666130-37c0-4ce7-8ce8-786ab236e1ae)

**Comment by melanielaporte** [comment]
All closed 20231109
