### ISSUE TITLE
PCB, Add SilkScreen, Board Name, Version, License, OpenHardware Logo

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#106]
In addition to the Public Invention logo there now, add the Board Name, Version, License, Open Hardware Logo to the silk screen on the controller and the heater.

Similar to the text on the GPAD
![image](https://github.com/PubInv/moonrat/assets/5836181/a110cb3c-c9c6-46cb-bd23-cd246afc2901)

**Comment by ForrestErickson** [comment]
Also a place to write the serial number.

![image](https://github.com/PubInv/moonrat/assets/5836181/71b3c61c-7c4b-467e-93a1-aaf1affcc086)

**Comment by melanielaporte** [comment]
Done on 20231112
