### ISSUE TITLE
Reminder: capture the traffic regarding the JCLPCB order

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#108]
1. V-CUT
2. capture the BOM file
3. the placement file

**Comment by melanielaporte** [comment]
Ask JCLPCB that the V cut is on the User 1 layer - MAKE SURE THEY UNDERSTAND.

**Comment by ForrestErickson** [comment]
@melanielaporte 
This would be a good place for the JLCPCB emails regarding questions on our order.
