### ISSUE TITLE
Make or Find 3D model for Switch Key Cap, 

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#117]
On 20231114 Lee requested files from Omeron contact form at: https://components.omron.com/us-en/contact-us/inquiry?inquiry_summary=CAD%20data

### The Request
Would like 3D files for B32-1600
Our application is with switch B3F-1052
We want to import 3D file into KiCad which requires STEP and WRL. See: https://klc.kicad.org/model/m2/m2.1/

We also want to import into FreeCAD and so other file formats may be of use.

### Add 3D model to the MoonratII PCB.
Fit to SW1, SE2, and SW3
JLCPCB screen shot of this part.
![image](https://github.com/PubInv/moonrat/assets/5836181/0a362b3f-a976-424e-96d8-f6a4f4277e18)

**Comment by melanielaporte** [comment]
We have been instructed by JCLPCB to place special assembly instructions in the Other Information field to include the keycaps in the board order. Due to the lack of keycap footprint. 
One option is to hand assemble the keycaps instead of JCLPCB.

**Comment by melanielaporte** [comment]
@melanielaporte Send JCLPCB 3D renders to better illustrate our goal. 20231116!

**Comment by ForrestErickson** [comment]
Notes from drawing on the Key Cap B32-1600
![image](https://github.com/PubInv/moonrat/assets/5836181/5cd8fbbf-5e8e-4140-b4d9-290188986b5d)
