### ISSUE TITLE
JCLPCB cannot do the V-cut with current files today

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#118]
If you want to add a V-cut, you must add edge rails to make panel >=70mm each sides , and can only select standard assembly option.
<img width="355" alt="Screenshot 2023-11-15 at 4 44 39 PM" src="https://github.com/PubInv/moonrat/assets/107901386/0699f8a3-8f3f-4632-8846-448350d40850">

**Comment by ForrestErickson** [comment]
The layer "User Comments" may be the expected layer for V-Cut aka V-score

See: https://github.com/Bouni/kicad-jlcpcb-tools/pull/161
