### ISSUE TITLE
Add New OLED Footprint to Schematic and Pull Into PCB, Add 4x SMD Nuts, Add 4x M2x6mm Phillips Pan Head

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#124]
Lee created a new OLED footprint.
This footprint will work with the JLCPCB SMD round nut to mount the OLED with a 2Mx6 screw

SMD Round nut:
TH162050CTJ
Manufacturer Sinhoo
MFR.Part # TH162050CTJ
JLCPCB Part # C3020130
https://jlcpcb.com/partdetail/Sinhoo-TH162050CTJ/C3020130

M2x6 screw
McMaster Carr PN: 92005A023
https://www.mcmaster.com/92005A023/

Will need to add four of each to the schematic as non PCB parts, BOM only.

**Comment by melanielaporte** [comment]
Done on 20231120.
