### ISSUE TITLE
Land Pattern Hole Size for SMT Steel Spacer With Internal Thread

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#131]
Reference:
https://www.we-online.com/components/products/datasheet/9774050243R.pdf

Make hole 10% oversize
So 2.5 spacer needs 2.68mm plated hole.

The JLCPCB spacer is brass.

**Comment by melanielaporte** [comment]
Related to the enclosure.

**Comment by melanielaporte** [comment]
Closed as JLCPCB was able to built PCB design without asking for additional changes.
