### ISSUE TITLE
JLCPCB Order Problem with the SMT Assembly

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#136]
I received the email below from JLCPCB today. 

![Screenshot Capture - 2023-11-30 - 09-44-41](https://github.com/PubInv/moonrat/assets/107901386/e6136e16-8c31-4128-bb62-78f28d3f2e2a)

**Comment by ForrestErickson** [comment]
While I can guess there is insufficient information to be sure.   Please forwarded to me and Robert the email you received.
When asking about orders it is important to refer to order numbers and part number and so on as to make the conversation VERY specific.

My guess.  This is a question associated with the PCB order and not the order of Assemblies. Remember how I said confusion abounds over PCBs versus Assemblies. And that is why I try to avoid ever referring to something with components soldered to it as other than an assembly.
Under that assumption, therefore the notes about assembly i the PCB order do not apply.  I suggest you review the order and if I am correct write an email to JLCPCB clarifying that. Copy Robert and me.

**Comment by melanielaporte** [comment]
![Screenshot Capture - 2023-12-02 - 12-25-42](https://github.com/PubInv/moonrat/assets/107901386/66cb0cfc-33f2-473c-b3da-491943e10f42)

**Comment by melanielaporte** [comment]
![Screenshot Capture - 2023-12-02 - 12-37-41](https://github.com/PubInv/moonrat/assets/107901386/df35090b-7182-4375-91c2-cb65d3aa5563)

**Comment by melanielaporte** [comment]
Invoice paid 12/03/2023.
Issue complete.
![Screenshot Capture - 2023-12-05 - 23-03-46](https://github.com/PubInv/moonrat/assets/107901386/ecd58d1b-0760-4607-9f62-94e6458910c1)
