### ISSUE TITLE
Related to Issue #55: JLCPCB V-cut requires a larger board dimension

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#147]
The problem: changing the PCB/assembly board width will change the enclosure dimensions. 
Please update the schematic in Kicad and send new schematic drawing to the enclosure team. 
![Screenshot Capture - 2023-12-05 - 23-01-26](https://github.com/PubInv/moonrat/assets/107901386/579463c6-9d5e-4947-8dc1-99b98669663d)

**Comment by ForrestErickson** [comment]
This will be fine as the added rails are also V cut (Assuming I understand what I see) We (Melanie) will simply snap them off.

Since this is my first work with V-CUT as a designer I am learning.
