### ISSUE TITLE
 JLCPCB Order issue with Q1, BZ1, J9, J11, and J6  component orientation 

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#153]
![Screenshot Capture - 2023-12-07 - 04-53-02](https://github.com/PubInv/moonrat/assets/107901386/b0d27d7a-81c8-4260-9f45-65cf7d810410)

**Comment by ForrestErickson** [comment]
These screen shots helps understand the orientation. 

![image](https://github.com/PubInv/moonrat/assets/5836181/1aa6bfee-65d9-448e-9d7e-b72b05ed5f53)

![image](https://github.com/PubInv/moonrat/assets/5836181/f7eec79b-c1bb-402d-939f-1ef94f402fff)

**Comment by melanielaporte** [comment]
As it stands, the issue has been solved.
