### ISSUE TITLE
Capture Presentation on Laplace Transform of PID

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#200]
@cfergu11 

May I ask you to capture your Laplace Transform presentation from yesterday's meeting into the body of this issue for my future reference please?

Thanks,
Lee

**Comment by kurama79** [comment]
Hi Lee,
Sure, no problem. The model or Laplace transformation that I showed in the meeting is an approximation of a linear behavior, a linear behavior is just like a first-order system wherein the time domain is like a delayed exponential function $e^{t-a}$ where $a$ is the delay. In other words, the model presented $\frac{K e^{-Ls}}{Ts + 1}$ is an approximation to estimate the behavior of the plant, where $K$ is the setpoint value, $L$ is the time when we assume the plant evolve begin, and $T$ is the time that we assume the plant reaches the setpoint (without control). To refer to more information you can take a look at the next info:

- Modern Control Engineering, Katsuhiko Ogata, 5th edition.
- [https://www.realpars.com/blog/pid-controller](url)
- Rakesh P. Borase, D. K. Maghade, S. Y. Sondkar, S. N. Pawar, "A review of PID control, tuning methods and applications", International Journal of Dynamics and Control, vol. 9, pp. 818 – 827, 202, doi: https://doi.org/10.1007/s40435-020-00665-4

I hope the above helps.

**Comment by kurama79** [comment]
And... 
Here is a part of the book where it explains the model estimation.
[pid_ogata.pdf](https://github.com/PubInv/moonrat/files/14275170/pid_ogata.pdf)

**Comment by ForrestErickson** [comment]
@kurama79 
I have reviewed the article "A review of PID control, tuning methods and applications" by Rakesh P. Borase1,2 · D. K. Maghade3 · S. Y. Sondkar1 · S. N. Pawar2
Some of it I follow and some make reference to idea I do not follow but it all helps.

You wrote, " first-order system wherein the time domain is like a delayed exponential function  where  is the delay. "
I am reminded of how a co worker explained to me that stabilizing a feedback system often has to be done where one delay (or rise time) is larger than all the others and then the design is done around that delay (rise time) and called such design dominant pole design which I assume becomes equivariant to first order.

As a physicist I also want to understand what physical phenomena become the influence on the control terms. 
For the incubator we put heat in to increase the temperature to the desired incubation temperature and if the system is in equilibrium then the heat in must equal the heat loss through the thermal resistance of the incubator to the ambient environment.  And with the assumption that the temperature is only on the order of about body temperature or similar there is not significant radiation loss and so loss by conduction and convection to air will dominate and the assumption of Newton's Law of Cooling applies and the heat losses are proportional to temperature difference.  This assumption can and should be tested for every incubator we develop. We simply set up the MoonratII controller to put a constant power (PWM) into the heater and measure the temperature rise above ambient for several PWM values.
So we could develop a table. Other measurements to make is the temperature rise time and the fall time as these will help us understand and quantify the thermal resistance to ambient and the heat capacity of our incubators.
A table for each incubator design will be desirable. And we may want to characterize with and with out loaded with petri films. See below.

Since you recommended the Laplace model I wonder, do you have previous experience modeling such real world systems?
I do not have significant experience. It is approximately only book learning I have.  I would like to transform my book learning to real world.

## Example Tables for Characterizing Incubators and Heaters
Each named system will have a characteristic thermal conductance and heater system. The name should reflect the incubator construction.
An experiment must be made to find the 1/e thermal rise / fall time for each PWM setting.

### Incubator Name1

| **PWM** 	| **Temp Rise** 	| **RiseTime** 	| **Fall Time** 	| **Notes** 	|   	|   	|
|---------	|---------------	|--------------	|---------------	|-----------	|---	|---	|
| 1%      	|               	|              	|               	|  Empty         	|   	|   	|
| 5%      	|               	|              	|               	|  Empty         	|   	|   	|
| 10%     	|               	|              	|               	|  Empty        	|   	|   	|
| 15%     	|               	|              	|               	|  Empty         	|   	|   	|
| 20%     	|               	|              	|               	|  Empty         	|   	|   	|
| ??%     	|               	|              	|               	|  Empty         	|   	|   	|


### Incubator Name2

| **PWM** 	| **Temp Rise** 	| **RiseTime** 	| **Fall Time** 	| **Notes**     	|   	|   	|
|---------	|---------------	|--------------	|---------------	|---------------	|---	|---	|
| 1%      	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
| 5%      	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
| 10%     	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
| 15%     	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
| 20%     	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
| ??%     	|               	|              	|               	| 25 Petrifilm™ 	|   	|   	|
