### ISSUE TITLE
PWA #2 Pin Issue - Smoke

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#202]
Pin 12 & 13, has caused burning smell.

**Comment by HJGV05** [comment]
Hi Melanie @melanielaporte ! have you solved this problem? have you checked that the other pins have no continuity between them? (I'm catching up with the issues hehe) greetings.

**Comment by melanielaporte** [comment]
Hi! Yes, I have just solved the pin issue. At this moment, I am now working on connectivity between your code and the boards. 
Lee has 2 sets of boards as of last weekend and has successfully connected the entire system. We will show our progress tomorrow night. I hope to order PCB version 2.0 very soon so we can begin the build. 

https://github.com/PubInv/moonrat/assets/107901386/a3397e30-9779-48df-a8b8-922d29bdf51d

**Comment by melanielaporte** [comment]
@HJGV05 @ForrestErickson Hi! Yes, I have just solved the pin issue. At this moment, I am now working on connectivity between your code and the boards.
Lee has 2 sets of boards as of last weekend and has successfully connected the entire system. We will show our progress tomorrow night. I hope to order PCB version 2.0 very soon so we can begin the build.


https://github.com/PubInv/moonrat/assets/107901386/c6d716ca-b6b0-4860-a24c-6b4cbcac998f

Sound up!

**Comment by melanielaporte** [comment]
@ForrestErickson

**Comment by melanielaporte** [comment]
Smoke issue solved.
