### ISSUE TITLE
Capture Example "Incubator" Characteristics

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#204]
As and example of characterizing an "incubator" I will do so on a system I have in my lab.
And as an example of adding information to the Github Moonrat repository I will make notes here.

My setup.
I have a fork of the moonrat repository to my Github account
My fork is at: https://github.com/ForrestErickson/moonrat_atForrestErickson
I have a local clone of my repository on my Windows 10 PC.

I have made some new folders and will place information about system which I already have and can act as a practices "incubator" into my local repository.
![image](https://github.com/PubInv/moonrat/assets/5836181/9cfbae13-6951-4c17-9b61-dca64833907e)

The new path is enclosure_mooonratII\Incubators\Can21Oz
I made a README.md file in a text editor.

Using the git CLI (command line interface ) you can see that I now have an untraced file in a folder called " Incubators/"
![image](https://github.com/PubInv/moonrat/assets/5836181/2cedfc2b-50e1-40a3-86a7-16111a493087)
You can not add an empty folder to a git repository but since my folder has that README.md in it I can use the following command
"git add Incubators/" and press enter
![image](https://github.com/PubInv/moonrat/assets/5836181/ca809278-075a-4a6e-a4e2-993335c1571b)

Now when I do a "git status" command 
![image](https://github.com/PubInv/moonrat/assets/5836181/3d1df358-0099-435b-8f9b-baa781ebdf8a)
we see that the new file in the new folder has been added (staged) for commit.
I then commit the staged file.
![image](https://github.com/PubInv/moonrat/assets/5836181/1c4d0f1d-c3b2-41e9-9b37-691440e3fd05)

I then do a pull from my forked repository (because it is good practice that you allways do so.)
![image](https://github.com/PubInv/moonrat/assets/5836181/1e75057f-bc6d-4950-9faa-2bc6fea977d2)
This brought in changes since my last pull.
I had to accept and make a merge note which I did using the default editor, Nano.
![image](https://github.com/PubInv/moonrat/assets/5836181/fef97fda-fb3d-4f48-80c6-390edb082bcd)

Next I pushed
![image](https://github.com/PubInv/moonrat/assets/5836181/36e42ac9-b741-4cbb-81c1-0077f47c4f8c)

Open my Fork and navigate to the new folder and see the README.md
![image](https://github.com/PubInv/moonrat/assets/5836181/ebc5b6ba-c798-4a88-96e4-8afcbcddde26)

Next I made a "Pull Request" to the Public Invention upstream repository for Moonrat
![image](https://github.com/PubInv/moonrat/assets/5836181/b127fc9a-5d19-4ec2-95e0-4bca4882f956)

![image](https://github.com/PubInv/moonrat/assets/5836181/42678fab-5000-4c54-a70e-0ae052653bc2)

![image](https://github.com/PubInv/moonrat/assets/5836181/fcb2b2ee-6cfc-4b9f-b07c-5b9b6dbff458)

![image](https://github.com/PubInv/moonrat/assets/5836181/107d3e65-26f3-4e8c-80a1-68f10c540d29)

![image](https://github.com/PubInv/moonrat/assets/5836181/0de1340a-2e4d-4118-b048-3af286b040a9)

And my changes have been merged into the upstream repository.

If you update your fork or clone you will now have the changes.

**Comment by ForrestErickson** [comment]
Once the README.md file is in the folder of the repository it is the default information seen when you havigate to the folder.
![image](https://github.com/PubInv/moonrat/assets/5836181/b2df8dd0-5e69-44e0-aa31-48ff888c087c)

There is a nice way to edit it through a web browser. 
I will fix the lines that did not wrap as expected to show how it is done.
Markdown requires two spaces at the end of a line to signal a carrage return and line feed (so to speek) which I did on all the lines.
![image](https://github.com/PubInv/moonrat/assets/5836181/b46d6905-c4d4-41a2-8b30-086b44a0ee96)

When save this is the new view which is easier to read.
![image](https://github.com/PubInv/moonrat/assets/5836181/84c17cfe-a2ca-423a-95e7-c21575d7c01b)

I will have to contribute this change from my fork to the upstream.
![image](https://github.com/PubInv/moonrat/assets/5836181/adbae619-6cd8-4bbe-8ea2-a5460336f1db)

![image](https://github.com/PubInv/moonrat/assets/5836181/dd2b3db2-dbf2-47be-8698-a310fa125188)
![image](https://github.com/PubInv/moonrat/assets/5836181/177c6125-3408-45d4-8c3c-da5a04028d12)
![image](https://github.com/PubInv/moonrat/assets/5836181/982e405c-9ef8-4e03-b775-eaa9eb63a4c4)
![image](https://github.com/PubInv/moonrat/assets/5836181/c2c60cb2-af7f-4c20-801e-9c2b3fb244e1)

And it is done.

**Comment by ForrestErickson** [comment]
I have captured characterisics of an "incubator" into the repository as a template for documenting such an incubator. This issue was to capture the steps of making a Markdown document in a folder, a  README.md. 

Such README.MD files are a way to capture and document information in a folder which for a visitor is easy to read.

Closing this issue.

**Comment by HJGV05** [comment]
Thank you very much for the guide Robert! I am ordering my own folder to manage it this way in the future, Silvia has also shared with me a very useful video about it: https://www.youtube.com/watch?v=VdGzPZ31ts8&ab_channel=HolaMundo
Greetings!
