### ISSUE TITLE
Key Caps Wrong Size For Switch, Version 1 JLCPCB Build

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#211]
The square retention feature of the key caps are way to large for these switches.

Need to look for other JLCPCB part number Key Caps. 

Need to identify and order a correct key cap for SN 1-5.

**Comment by ForrestErickson** [comment]
@melanielaporte 
Lets review the data sheets for the switch and the key caps and figure out where I went wrong.

My guess is that one data sheet has key caps for multiple size switches.

**Comment by melanielaporte** [comment]
Great, I have time tomorrow before the meeting or Wednesday, both after 5:30pm.

**Comment by melanielaporte** [comment]
Ok @ForrestErickson I have time to meet tomorrow or Wednesday, both after 5:30pm

**Comment by melanielaporte** [comment]
v2 Order

Keycap number JLCPCB part number: C87037 MFR.Part #
B3F-1052

Update switch cap from B3F-1052 to B32-2000



Digikey - appropriate keycaps d
Mouser...

<img width="919" alt="Screenshot 2024-02-28 at 7 04 55 PM" src="https://github.com/PubInv/moonrat/assets/107901386/80183520-a81c-4a15-a386-ac8c8649f6a1">

**Comment by ForrestErickson** [comment]
20240301 Update schematic with Digikey part number.
