### ISSUE TITLE
No Factory Test Firmware in Repository Folder

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#212]
IIRC Melanie was putting firmware for factory test into the repository I expected to find it but this folder is empty.

https://github.com/PubInv/moonrat/tree/main/moonratII/firmware_moonratII/factoytest

**Comment by melanielaporte** [comment]
That was for Horacio to accomplish. I will add it though.

**Comment by melanielaporte** [comment]
Added.
