### ISSUE TITLE
ECO, Moonrat II Controller PCB version 1, Jumper D8 D10

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#216]
## Summary
Change for PWM into Heater Transistor Q1.
The PID algorithms produce an analog (PWM) control signal. The Pin D8 is GPIO only.  D10 is an unused pin which supports PWM. 

###  Hardware Rework
For circuit board Version 1.0: Add a jumper wire from D8 to D10

### Firmware Change
Change firmware to support PWM on pin D10.   
**CAUTION: To prevent contention, Pin D8 MUST remain high impedance (INPUT).**

**Comment by ForrestErickson** [comment]
### Configuration Records
Record here, by serial number of the MoonRatII Version 1 PCBs for the Jumper D8 to D10 rework.

| **Serial #** 	| **Disposition** 	| **Date of Rework** 	|
|--------------	|-----------------	|--------------------	|
| 1            	| Lee             	| 20240220           	|
| 2            	|                 	|                    	|
| 3            	|                 	|                    	|
| 4            	| Lee             	| 20240220           	|
| 5            	|                 	|                    	|

**Comment by ForrestErickson** [comment]
20240301 Update schematic and Version 2 PCB.
