### ISSUE TITLE
Order Rev 2 PWA and PCBs, 

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#224]
## Files to Generate
- [x] Review Design for Manufacturing JLCPCB
- [x] Schematic Rev v2 PDF
- [x] PCB Rev 2 PDF
- [x] Update the [KiCanvas links](https://github.com/PubInv/moonrat/tree/main/moonratII/pcb_moonratII) to the live viewer (Kicanvas), schematic and PCB
- [x] Generate BOM (Bill of Material),  Break in to sub BOMs for JLCPCB, DigiKey, Aliexpress, Other.
- [x] Generate 3D files of PWA (Printed Wiring Assembly) (With and without the UNO?)
- [x] Export gerber and placement files (for JLCPCB)
- [x] Review gerber files
- [x] Order JLCPCB
- [x] Order Digikey
- [x] Order Aliexpress
- [x] Order Other?

**Comment by ForrestErickson** [comment]
Review for Manufacturier requirements
KiCad before setup
![image](https://github.com/PubInv/moonrat/assets/5836181/327e2dbf-7df0-43b1-9800-5fef21bfc9d7)

**Comment by ForrestErickson** [comment]
## Verify that the TMP36 is out put values that make sense.
At room temparature of about 73 degrees we had 0.75 V

Here is a graph where about mid way Lee pinched the TMP36 between fingers and the output rise a bit.
![image](https://github.com/PubInv/moonrat/assets/5836181/4dab67ff-858a-4176-bd75-a817743a43fe)

### Conclusion
The TMP36 is wired correctly

**Comment by melanielaporte** [comment]
![Screenshot Capture - 2024-03-16 - 13-53-54](https://github.com/PubInv/moonrat/assets/107901386/6ec5b232-04cd-4656-a4b9-e6828750b626)

**Comment by melanielaporte** [comment]
@ForrestErickson 
We have changed the Uno type from Uno to R4 Minima. 6 R4 were ordered 20240316 for the Rev 2 prototypes and shipped to GDL team. 
Future plans: order R4 for the US team as they are still working with the old Unos.

![Screenshot Capture - 2024-03-16 - 13-53-54](https://github.com/PubInv/moonrat/assets/107901386/6ec5b232-04cd-4656-a4b9-e6828750b626)
cc: @RobertLRead
