### ISSUE TITLE
Observe 50-60 mV Ripple on TMP36 Power

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#226]
## Summary

Observed Ripple on power supply of the temperature sensor at 300 KHz of 50 tp 60 mV

![image](https://github.com/PubInv/moonrat/assets/5836181/f4a692a9-6f49-429a-b659-ef167df5ad8d)

## System Under Test
MoonratII SN01 Rev 1 PCB
Powered off of USB port. 
Firmware: factoryTest firmware of 20240302

This ripple is (0.06/5)*100 = 1.2%

**Comment by ForrestErickson** [comment]
Consider adding JLCPCB part
https://jlcpcb.com/partdetail/Yageo-CC0603KRX7R9BB104/C14663

**Comment by melanielaporte** [comment]
Will not fix.
