### ISSUE TITLE
Screw distributor issue 

### ISSUE THREAD

**Issue by SilviaKarbid** [PubInv/moonrat#238]
Put here screw distributors in Guadalajara 

![Captura de pantalla 2024-03-20 223140](https://github.com/PubInv/moonrat/assets/31602139/c8e9cf32-ac7f-487f-a046-eafefb4648c7)

**Comment by SilviaKarbid** [comment]
I found this, and then have a place here in Guadalajara to pick the screw
https://www.torec.mx/products/tqp2x6
![image](https://github.com/PubInv/moonrat/assets/31602139/7fe4a187-cb20-4cbf-98dc-1bdae69461e9)
![image](https://github.com/PubInv/moonrat/assets/31602139/5652c427-f5c4-4899-b776-41bd0b5e8699)

**Comment by SilviaKarbid** [comment]
They accept paypal

**Comment by ForrestErickson** [comment]
The screw type should be pan head which has a flat face against the OLED PCB.

@SilviaKarbid 
Can you find one meeting those requirements?

**Comment by SilviaKarbid** [comment]
I will check 🙂
