### ISSUE TITLE
Is There and Ideal Number or Number of Petri Films an Incubator Should Hold?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#245]
What is the quantity in which pitri films are packaged?
Is there a logical number the incubatore should hold for an optimal usage (assuming no loss or assuming one of TBD are lost)?

**Comment by RobertLRead** [comment]
20, but perhaps two groups of 20

Robert L. Read, PhD
Twitter: @RobertLeeRead @pubinvention
Public Invention: https://www.pubinv.org
Join Our Mailing list: ***@***.***
YouTube: https://www.youtube.com/channel/UCJQg_dkDY3KTP1ybugYwReg
Medium: ***@***.***
