### ISSUE TITLE
Overheating Problem URGENT 

### ISSUE THREAD

**Issue by SilviaKarbid** [PubInv/moonrat#266]
### Heater Sensor Overheating
The temperature sensor board we received seems to have an overheating issue. This is causing the sensor to malfunction and provide inaccurate readings. When testing the temperature sensor board at 12V, the PCB experiences excessive heating, making the temperature readings unreliable and not reflective of the actual temperature at the incubator.

### UNO InCompatibility
There also seem to be compatibility issues between the R3 and R4 boards, as the R4 board does not function properly when tested on both boards.
Has anyone tested the board to see if they are also experiencing any of the previously mentioned issues?
![WhatsApp Image 2024-05-20 at 6 50 07 PM](https://github.com/PubInv/moonrat/assets/31602139/00d33634-0d6d-4929-aad1-050d3c9e4890)

**Comment by ForrestErickson** [comment]
Review with Silvia the issues
Regarding UNO InCompatibility
There also seem to be compatibility issues between the R3 and R4 boards, as the R4 board does not function properly when tested on both boards.


### Description of hardware during test.
The Controller is an UNO R3.
Device under test powered only from the USB. There was no connection to the power jack.
The R3 is able to read the temperature sensor.  And the readings make sense.  Used lighter (fame) near the sensor.

### Suspected Problem
The current through the Schoktee Diode is heating the diode.  The diode was for reverse polarity protection. and can be defeated (Shorted out).

### Fix to try
Short out D1 and retest.
