### ISSUE TITLE
Lee wants to Order UNO R4, Which One?  WiFi or Minimua or ???

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#278]
Hello team,

Lee wanted to order an UNO R4 but discovered on Amazon that there is no such thing. There are several.
![image](https://github.com/PubInv/moonrat/assets/5836181/9f7c8236-e4a2-4421-a959-ea1bc025fe68)

Which R4 do the users in Guadalajara have?

**Comment by SilviaKarbid** [comment]
Hi Lee!, we use this one, but we think that maybe the WiFi module make some interference with the voltage, I don't know if you want to try the R4 minima ![image](https://github.com/PubInv/moonrat/assets/31602139/5f34768f-e960-4a15-98df-4fe90e8703f9)

**Comment by ForrestErickson** [comment]
FYI,
I have placed an order for one and will soon have it.
![image](https://github.com/PubInv/moonrat/assets/5836181/0ed07b12-6502-420b-8776-d7ac34b03c93)

**Comment by RobertLRead** [comment]
I have two R4 minimas. I plan to start building soon; hopefully we will have a confirmation that that works soon.

**Comment by RobertLRead** [comment]
@ForrestErickson : We are using R4 Minimas; that is what you should order, I am closing this issue.
