### ISSUE TITLE
Apply for OSHWA certification

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#294]
https://application.oshwa.org/apply

**Comment by RobertLRead** [comment]
![Screenshot 2024-07-30 at 6 46 46 PM](https://github.com/user-attachments/assets/fb3ca7f9-4fce-478c-859f-a0f494482652)

**Comment by RobertLRead** [comment]
I applied for OSHWA certification on July 30th, 2024. It says it can a few weeks.

**Comment by RobertLRead** [comment]
We received this certification number:

US002666

We should add the mark to the README.

**Comment by melanielaporte** [comment]
Added to Overleaf.
