### ISSUE TITLE
Fundamental Modularity: The 6-wire appliance, Choose Connector, J6  and J9

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#31]
Fundamental Modularity: The 6-wire appliance
The electronic elements of this incubator can be separated into two modules. As usual, identifying this modularity allows improvements in our ability to evolve the design. The heat-insulation thermos is a third module.

Call the part that goes into the thermos the "appliance" and the parts that are outside it the "controller". The appliance consists of a heating element and a thermometer, the wires and a connector. The controller consists of a microcontroller, an electronic power circuit, and some means of programming the controller, all packed into an enclosure.

The "appliance" needs only 6 wires:

GND (ground, nominally voltage 0.)
+12V PWR (the heating elements requires approximately 12V power.)
HEAT ON (Vin)
+5V (for the thermometer).
SIG -- data from the digial "one-wire" format
UNK - a final wire is included for future functionality that is unknown right now.
These (esp. the power) should probably be rated for 2 amps, but in practice 1 amp is probably good enough.

We have not yet chosen the connector, but we would like the connector to be of minimal width, so, for example, a 3x2 JST layout would be better than 6 pins in line.

**Comment by ForrestErickson** [comment]
Lee reviewed the current rating per pin on RJ45 connectors and found they are only rated at 1.5A per pin so not much margin .  If two pins had +5 and two pins had GND it would have some redundancy.  

Still looking for ideas.

**Comment by ForrestErickson** [comment]
Inexpensive, Off the shelf 10 conductor ribbon cable
https://www.amazon.com/gp/product/B01DP13EDA/ref=ox_sc_saved_title_2?smid=A64W1E1ZZHST0&th=1
![image](https://github.com/PubInv/moonrat/assets/5836181/3725a140-de95-4c3d-b7c8-ac515fcb73e0)


What appears to be the mating connector:
https://www.digikey.com/en/products/detail/molex/0702461001/760166
![image](https://github.com/PubInv/moonrat/assets/5836181/e89d6cff-6f46-4c88-9c8d-a0d46d349391)

**Comment by ForrestErickson** [comment]
Another idea is the molded connectors used for automotive lights to trailers.

https://www.amazon.com/807-Connectors-Extension-Connector-Way-Socket/dp/B07SR28CG4/ref=sr_1_1

**Comment by magnetictheory** [comment]
Image of automotive connector: [807 Square 6-Way Trailer Wiring Harness Connectors,6 pin Square Trailer Wire Extension for LED Brake Tailgate Light Bars, Hitch Light Trailer Wiring Harness Extension Connector (6 Way-Socket)](https://www.amazon.com/807-Connectors-Extension-Connector-Way-Socket/dp/B07SR28CG4/ref=sr_1_1)

![image](https://github.com/PubInv/moonrat/assets/107901386/9d2bd9b7-1aab-47da-9e47-5b3ed2d58967)

**Comment by ForrestErickson** [comment]
@melanielaporte 
See what we found!!!!

At JLCPCB found 2x5 plug
https://jlcpcb.com/partdetail/boomele_boom_Precision_elec-C5665/C5665

![image](https://github.com/PubInv/moonrat/assets/5836181/ad42b9fa-2cfd-4ba6-acdf-b6cdcf2c8468)

Manufacturer BOOMELE(Boom Precision Elec)
MFR.Part # C5665
JLCPCB Part # C5665

**Comment by ForrestErickson** [comment]
Have placed the following in to the PCB:
Manufacturer BOOMELE(Boom Precision Elec)
MFR.Part # C5665
JLCPCB Part # C5665

**Comment by ForrestErickson** [comment]
Have placed the following into the PCB:
0.4614	1x6P 20A -40℃~+105℃ 300V Green 12~30 Straight pin 5.08mm 2.5 1 6 Plugin,P=5.08mm Screw terminal ROHS	JLCPCB	C2915642			DB128V-5.08-6P-GN-S	DIBO

**Comment by ForrestErickson** [comment]
@melanielaporte 
This may be ready to close out. The PCB has a screw terminal which will work with the automotive connector. The PCB also has the IDC header which is an alternative way to connect too. 

We need to check that we have a BOM only part for the automotive connectors and or the IDC cable.

**Comment by melanielaporte** [comment]
Complete. Has been added to the schematic.

**Comment by melanielaporte** [comment]
Ordered cable connectors for J9 and J6

https://www.amazon.com/CARROFIX-Trailer-Extension-18-Gauge-Connector/dp/B08B4PBGGR/ref=pd_rhf_sc_s_pd_sbs_rvi_sccl_2_2/143-1165672-2295435
