### ISSUE TITLE
Add R-value report

### ISSUE THREAD

**Issue by kurama79** [PubInv/moonrat#343]
Hi everyone, in this commit https://github.com/PubInv/moonrat/pull/338 is the report and some helpful
Images to see the current consumption.
@SilviaKarbid @HJGV05 @melanielaporte @RobertLRead

**Comment by ForrestErickson** [comment]
@kurama79 
How do I look at this report?

**Comment by kurama79** [comment]
Hi @ForrestErickson ,
All is in this path moonratII/enclosure_mooonratII/energy_consumption
