### ISSUE TITLE
Configure MOSFET / BJT as Switch Not Follower

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#46]
## Consider Configure MOSFET / BJT as Switch Not Follower
The schematic from https://github.com/PubInv/moonrat/blob/master/moonrat/schematic.jpg shows the BJT in an emitter follower configuration. This means that the typical 0.7V Vbe drop and some saturation voltage will be subtracted from the  voltage supply to the heater element.  
In the schematic worked up on 20230620 by volunteers we have a MOSFET wired in a source follower. This would probably be even worse as the Vgs ranges from 2 to 4 Volts.
If the BJT or MOSFET were to be wired as a switch we would have either the VSat of the BJT (about 200mV) or the RDSon =44mOhm of the MOSFET. At 2.5 Amps the Vds will be 2.5*0.044= 0.11 Volts.

### For Design Insight on Transistor As Switches Read:
For BJT:
https://www.circuitbread.com/tutorials/how-to-use-a-bipolar-junction-transistor-bjt-as-a-switch

For MOSFET:
https://www.electronics-tutorials.ws/transistor/tran_7.html

**Comment by melanielaporte** [comment]
Completed.
