### ISSUE TITLE
Add Key Caps to Switches

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#53]
@melanielaporte 
We should also add a key cap three times to the schematic 
https://www.digikey.com/en/products/detail/omron-electronics-inc-emc-div/B32-2010/1811718
This part will be not electrically connected but will be on the BOM.

**Comment by melanielaporte** [comment]
20231112: changed key cap to B32-1600
Datasheet - https://omronfs.omron.com/en_US/ecb/products/pdf/en-b32.pdf
<img width="1400" alt="Screenshot 2023-11-12 at 4 45 40 PM" src="https://github.com/PubInv/moonrat/assets/107901386/98701385-1d09-4b27-9985-259b29a9c1e9">

**Comment by melanielaporte** [comment]
Added to schematic.
