### ISSUE TITLE
When ordering the PCB, ask manufacturer to V cut or score/gouge the PCB so we can snap it manually = 2 boards instead 1

### ISSUE THREAD

**Issue by melanielaporte** [PubInv/moonrat#55]

**Comment by ForrestErickson** [comment]
The Controller side must be seperated from the heater side. A V-Cut is the easy way to do this.

![image](https://github.com/PubInv/moonrat/assets/5836181/c21633eb-5257-4f80-8539-a6aa6889d12c)
The white line on Silk Screen currently shows the V-Cut but is just a place holder till we identify a good way to work with JLCPCB to identify , specify the V-cut.

Lee asked JLCPCB for advise and was referred to this link

https://jlcpcb.com/help/article/96-PCB-Panelization

**Comment by melanielaporte** [comment]
Vcut has been added to the PCB.

**Comment by melanielaporte** [comment]
Exact v-cut/v-score wording: 1. Please confirm V-cut is feasible on User 1 layer 
2. MF12 (1x4 header) should be soldered to J2 (OLED display) 
3. MF 4-6, 8 (round nuts) mounted to OLED display 4. MF1-3 (keycaps) to go on SW1-3
