### ISSUE TITLE
Added Fuse, Need PCB Footprint, 3D Model Too.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#64]
I replaced the series resistor on the power supply input with a polyfuse (It self resets when allowed to cool).
A PCB footprint is needed. Will have to make.

From the drawing:
![image](https://github.com/PubInv/moonrat/assets/5836181/9a938714-3473-4939-8443-b6c041daeca2)

For the part BSMD1812-300-16V
![image](https://github.com/PubInv/moonrat/assets/5836181/590cf662-cf2e-41e6-90fa-6402e7a1fbc3)

**Comment by ForrestErickson** [comment]
There is a place holder added to the PCB to remind us.

**Comment by ForrestErickson** [comment]
FYI I have added this same part to the controller schematic for the NASA-COG .

**Comment by melanielaporte** [comment]
Fuse has been added and committed. Done.
