### ISSUE TITLE
Orientation of J6 and J9 for Wire Connection Correct?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#80]
Is the orientation of J6 and J9 for wire connection correct.

![image](https://github.com/PubInv/moonrat/assets/5836181/da6713f3-fc17-4049-bbd7-2ef6ac41d7e1)

and

![image](https://github.com/PubInv/moonrat/assets/5836181/62d1f41e-3394-42b6-95ff-6570823d59d5)

This is wrong. We need to spin the J6 and J9 placement.

**Comment by melanielaporte** [comment]
Components successfully rotated!
