### ISSUE TITLE
Buzzer Hole Spacing or 3D Model Wrong

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#87]
The buzzer hole spacing appears to be wrong on the 3D view.

![image](https://github.com/PubInv/moonrat/assets/5836181/40a1a8ce-35ab-49d9-9cd0-d58ee7ff3588)

Does the PCB match the part?
Is the 3D render correct to the part?

**Comment by melanielaporte** [comment]
Check updated buzzer PCB position.

**Comment by melanielaporte** [comment]
10/21 We reviewed and confirmed that the error is ONLY the 3D model and the PCB spacing is 7.6mm. 
GPAD was built with this buzzer - https://www.digikey.com/en/products/detail/soberton-inc/WST-1210T/16354828?s=N4IgTCBcDaICwGYEFoDqBlAKsgjGHADNgHIAiIAugL5A
We are going forward with the GPAD. 
I will order 5 assembles and 5 raw boards, and 10 buzzer parts as back ups and for experiments.

**Comment by melanielaporte** [comment]
To do: Lee will make a new 3D model TBD.

**Comment by ForrestErickson** [comment]
Found a model here: https://grabcad.com/library/buzzer-12mm-continuo-1

![image](https://github.com/PubInv/moonrat/assets/5836181/b36b71d7-3f4e-4b6f-9bf5-764258314d6e)

Loaded into PublicInvention Library. 

@melanielaporte  will will need to connect the MoonratII with the Public Invention KiCAD library at some point. It is not cirtical for the order of PCBs however.

**Comment by melanielaporte** [comment]
Changed buzzer manufacturer to 
- Distributor 1 JCLPCB C360615
https://jlcpcb.com/partdetail/ss-SUN_12095_5VPA76/C360615#:~:text=Datasheet-,Download,-Source
and 
- Distributor 2 Adafruit P1536A

**Comment by ForrestErickson** [comment]
@melanielaporte 
I do not remember fixing this and suspect you did.
The buzzer 3D model is now correct.
![image](https://github.com/PubInv/moonrat/assets/5836181/dbcb7324-a131-44d5-83c4-9af7711afb0e)

Did you fix it?

Regardless you may close this issue.
