### ISSUE TITLE
Clearing Schematic Errors, Rev 0.1, "Pin not connected"

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#97]
Of the 33 schematic errors 30 are the pins on these connectors 

![image](https://github.com/PubInv/moonrat/assets/5836181/b09409fd-66aa-4e35-b811-9e1fb20b6fa5)

These pins need to be marked with the "x" no connect.

**Comment by ForrestErickson** [comment]
Set no connect marker on these pins and rerun ERC.

![image](https://github.com/PubInv/moonrat/assets/5836181/f9c3da18-c2d9-4c55-96fb-fd32a6ab4e6e)

Only three Errors left!

**Comment by ForrestErickson** [comment]
For VCCQ noi driven by a power pin.

![image](https://github.com/PubInv/moonrat/assets/5836181/44896ab4-cc39-48ff-8798-0ccae5a1f31f)

Try to clear by adding a power flag.
![image](https://github.com/PubInv/moonrat/assets/5836181/9d194b1f-da3b-4637-95e7-9109335a192c)

Rerun ERC and it worked.
![image](https://github.com/PubInv/moonrat/assets/5836181/97338291-1ead-4a5c-ae30-dfdf225c9982)

**Comment by ForrestErickson** [comment]
For the error
[power_pin_not_driven]: Input Power pin not driven by any Output Power pins
    ; Severity: error
    @(9600.00 mils, 5600.00 mils): Symbol U1 Pin 4 [GND, Power input, Line]

![image](https://github.com/PubInv/moonrat/assets/5836181/cc74f7a1-e739-4f4c-9bb9-70efc793de3f)

Try adding power flag.  Worked cleared the U1 Pin 4 error.
![image](https://github.com/PubInv/moonrat/assets/5836181/5c34ec6e-640a-4943-a47b-ea042019a761)

**Comment by ForrestErickson** [comment]
Lets add a power flag to +5P

![image](https://github.com/PubInv/moonrat/assets/5836181/91a1de20-1e9a-4e79-b00d-a151236578e5)


That cleared the last error.

**Comment by melanielaporte** [comment]
As intended, updated by marking pins not connected.
